# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3d60326a0e8b75b44cb7f36d7ebe1c27b949b11a286e92376f993fe50f746e602c756b2a79b1d2141f43760305081442cf52f68aa504ccefef62f3a036f858b

test:
  secret_key_base: 415bffe6683aa3d4473a3dea1bc53a42b8756eb119c30b6562b8f8f2faa4fbb621ae4721738be482bf1be79e43e38bc9c43b5884a4dac539cc7868173197f8b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
